name: Deploy React App

on:
  push:
    branches: [ master ]  # Trigger on push to the master branch (or your desired branch)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Run the workflow on Ubuntu virtual machines

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout your code from the repository
      
      - name: Use Node.js 16  # Specify the desired Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Replace with your desired version (check React compatibility)
      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Build React app
        run: npm run build  # Build the app for production (replace with your build command)

      - name: Deploy to GitHub Pages  # Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.REACT_APP_GITHUB_ACCESS_TOKEN }}
          publish_dir: ./build
