name: Deploy React App

on:
  push:
    branches: [ real-first-blog ]  # Trigger on push to the master branch (or your desired branch)

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Run the workflow on Ubuntu virtual machines

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout your code from the repository
      
      - name: Use Node.js 20  # Specify the desired Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 16  # Replace with your desired version (check React compatibility)
      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Build React app
        run: npm run build  # Build the app for production (replace with your build command)
      
      - name: Upload artifect
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build

      - name: Disable Jekyll by creating a .nojekyll file
        run: touch build/.nojekyll

      - name: Deploy to GitHub Pages  # Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
